/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataBase;

import java.awt.Color;

/**
 *
 * @author hossam
 */
public class MainFrameView extends javax.swing.JFrame {

    /**
     * Creates new form MainFrameView
     */
    int mouseX;
    int mouseY;
    public MainFrameView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        titleBar = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        databasebtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        homebutn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        aboutLabel = new javax.swing.JLabel();
        Settingsbtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        importbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fragmentsbtn = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        southContainer = new javax.swing.JLayeredPane();
        homePanel = new javax.swing.JPanel();
        viewDBlbl = new javax.swing.JLabel();
        gettingStartedLbl = new javax.swing.JLabel();
        importlbl = new javax.swing.JLabel();
        importPanel = new javax.swing.JPanel();
        dragNDroplbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        databasepanel = new javax.swing.JPanel();
        dbScrollPane = new javax.swing.JScrollPane();
        dbtable = new javax.swing.JTable();
        lipinski = new javax.swing.JCheckBox();
        leadLikness = new javax.swing.JCheckBox();
        bioavailability = new javax.swing.JCheckBox();
        exportbtn = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        SettingsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logPcomboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        maxHBD = new javax.swing.JTextField();
        maxHBA = new javax.swing.JTextField();
        maxLogp = new javax.swing.JTextField();
        Biolabel = new javax.swing.JLabel();
        bioThreshold = new javax.swing.JTextField();
        maxLogp1 = new javax.swing.JLabel();
        bioWeightscomboBox = new javax.swing.JComboBox<>();
        applybtn = new javax.swing.JPanel();
        applylbl = new javax.swing.JLabel();
        maxWeighttxt = new javax.swing.JTextField();
        fragmentsPanel = new javax.swing.JPanel();
        dbScrollPane1 = new javax.swing.JScrollPane();
        fragTable = new javax.swing.JTable();
        northcontainer = new javax.swing.JLayeredPane();
        northHome = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        northDatabase = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        structurelbl = new javax.swing.JLabel();
        northImport = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        northSettings = new javax.swing.JPanel();
        appName1 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        northFragments = new javax.swing.JPanel();
        appName2 = new javax.swing.JLabel();
        version1 = new javax.swing.JLabel();
        fragFileDragNDrop = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        searchBoxFragments = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        backGround.setAlignmentX(0.0F);
        backGround.setAlignmentY(0.0F);
        backGround.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backGround.setMinimumSize(new java.awt.Dimension(0, 0));

        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        sidePanel.setBackground(new java.awt.Color(0, 18, 50));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        databasebtn.setBackground(new java.awt.Color(32, 47, 90));
        databasebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databasebtnMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Database.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Database");

        javax.swing.GroupLayout databasebtnLayout = new javax.swing.GroupLayout(databasebtn);
        databasebtn.setLayout(databasebtnLayout);
        databasebtnLayout.setHorizontalGroup(
            databasebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasebtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        databasebtnLayout.setVerticalGroup(
            databasebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(databasebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(databasebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 60));

        homebutn.setBackground(new java.awt.Color(30, 61, 118));
        homebutn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebutnMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Home.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Home");

        javax.swing.GroupLayout homebutnLayout = new javax.swing.GroupLayout(homebutn);
        homebutn.setLayout(homebutnLayout);
        homebutnLayout.setHorizontalGroup(
            homebutnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homebutnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        homebutnLayout.setVerticalGroup(
            homebutnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homebutnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homebutnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(homebutn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, 60));

        aboutLabel.setForeground(new java.awt.Color(242, 241, 240));
        aboutLabel.setText("About");
        sidePanel.add(aboutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 890, -1, -1));

        Settingsbtn.setBackground(new java.awt.Color(32, 47, 90));
        Settingsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsbtnMouseClicked(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Settings.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Settings");

        javax.swing.GroupLayout SettingsbtnLayout = new javax.swing.GroupLayout(Settingsbtn);
        Settingsbtn.setLayout(SettingsbtnLayout);
        SettingsbtnLayout.setHorizontalGroup(
            SettingsbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsbtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsbtnLayout.setVerticalGroup(
            SettingsbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SettingsbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(Settingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 60));

        importbtn.setBackground(new java.awt.Color(32, 47, 90));
        importbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importbtnMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Import.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Import");

        javax.swing.GroupLayout importbtnLayout = new javax.swing.GroupLayout(importbtn);
        importbtn.setLayout(importbtnLayout);
        importbtnLayout.setHorizontalGroup(
            importbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importbtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        importbtnLayout.setVerticalGroup(
            importbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(importbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, 60));

        fragmentsbtn.setBackground(new java.awt.Color(32, 47, 90));
        fragmentsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fragmentsbtnMouseClicked(evt);
            }
        });

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Fragments.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Fragments");

        javax.swing.GroupLayout fragmentsbtnLayout = new javax.swing.GroupLayout(fragmentsbtn);
        fragmentsbtn.setLayout(fragmentsbtnLayout);
        fragmentsbtnLayout.setHorizontalGroup(
            fragmentsbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fragmentsbtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        fragmentsbtnLayout.setVerticalGroup(
            fragmentsbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fragmentsbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fragmentsbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(fragmentsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 70));

        homePanel.setBackground(new java.awt.Color(30, 61, 118));

        viewDBlbl.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        viewDBlbl.setForeground(new java.awt.Color(204, 204, 204));
        viewDBlbl.setText("View current database");

        gettingStartedLbl.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        gettingStartedLbl.setForeground(new java.awt.Color(204, 204, 204));
        gettingStartedLbl.setText("Getting Started");

        importlbl.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        importlbl.setForeground(new java.awt.Color(204, 204, 204));
        importlbl.setText("Import new chemicals");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gettingStartedLbl)
                    .addComponent(importlbl)
                    .addComponent(viewDBlbl))
                .addContainerGap(537, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(gettingStartedLbl)
                .addGap(33, 33, 33)
                .addComponent(viewDBlbl)
                .addGap(33, 33, 33)
                .addComponent(importlbl)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        dragNDroplbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/DragnDrop.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 61, 118));
        jLabel4.setText("Drag and drop sdf files:");

        javax.swing.GroupLayout importPanelLayout = new javax.swing.GroupLayout(importPanel);
        importPanel.setLayout(importPanelLayout);
        importPanelLayout.setHorizontalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importPanelLayout.createSequentialGroup()
                .addGroup(importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4))
                    .addGroup(importPanelLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(dragNDroplbl)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        importPanelLayout.setVerticalGroup(
            importPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, importPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(90, 90, 90)
                .addComponent(dragNDroplbl)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        databasepanel.setBackground(new java.awt.Color(30, 61, 118));

        dbScrollPane.setBackground(new java.awt.Color(204, 204, 204));
        dbScrollPane.setForeground(new java.awt.Color(0, 18, 50));
        dbScrollPane.setOpaque(false);

        dbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CD ID", "Formula", "weight", "ALERTS", "Lipinski violations", "Lead-likness violations", "Chemical beauty (QED)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dbtable.setFocusable(false);
        dbtable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        dbtable.setRowHeight(25);
        dbtable.setSelectionBackground(new java.awt.Color(222, 57, 95));
        dbtable.setSelectionForeground(new java.awt.Color(242, 241, 240));
        dbtable.setShowVerticalLines(false);
        dbtable.getTableHeader().setReorderingAllowed(false);
        dbtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbtableMouseClicked(evt);
            }
        });
        dbtable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dbtableKeyPressed(evt);
            }
        });
        dbScrollPane.setViewportView(dbtable);

        lipinski.setBackground(new java.awt.Color(30, 61, 118));
        lipinski.setForeground(new java.awt.Color(224, 222, 220));
        lipinski.setText("Lipinski ROF");
        lipinski.setContentAreaFilled(false);
        lipinski.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Unchecked.png"))); // NOI18N
        lipinski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lipinskiActionPerformed(evt);
            }
        });

        leadLikness.setForeground(new java.awt.Color(224, 222, 220));
        leadLikness.setText("Lead-likness");
        leadLikness.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Unchecked.png"))); // NOI18N
        leadLikness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadLiknessActionPerformed(evt);
            }
        });

        bioavailability.setForeground(new java.awt.Color(224, 222, 220));
        bioavailability.setText("Chemical beauty");
        bioavailability.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Unchecked.png"))); // NOI18N

        exportbtn.setBackground(new java.awt.Color(32, 47, 90));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Export");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Export.png"))); // NOI18N

        javax.swing.GroupLayout exportbtnLayout = new javax.swing.GroupLayout(exportbtn);
        exportbtn.setLayout(exportbtnLayout);
        exportbtnLayout.setHorizontalGroup(
            exportbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exportbtnLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(55, 55, 55))
        );
        exportbtnLayout.setVerticalGroup(
            exportbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exportbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(exportbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout databasepanelLayout = new javax.swing.GroupLayout(databasepanel);
        databasepanel.setLayout(databasepanelLayout);
        databasepanelLayout.setHorizontalGroup(
            databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasepanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(dbScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(databasepanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(lipinski)
                .addGap(39, 39, 39)
                .addComponent(leadLikness)
                .addGap(50, 50, 50)
                .addComponent(bioavailability)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        databasepanelLayout.setVerticalGroup(
            databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasepanelLayout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, databasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lipinski)
                        .addComponent(leadLikness)
                        .addComponent(bioavailability))
                    .addComponent(exportbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(dbScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        SettingsPanel.setBackground(new java.awt.Color(30, 61, 118));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("LogP calculation method");

        logPcomboBox.setBackground(new java.awt.Color(0, 18, 50));
        logPcomboBox.setForeground(new java.awt.Color(242, 240, 241));
        logPcomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AlogP", "XlogP", "MannholdLogP" }));
        logPcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPcomboBoxActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Max Hydrogen bond Acceptors");

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Lead-Likness filter values :");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Max weight");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Max Hydrogen bond donors");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Max LogP values");

        maxHBD.setBackground(new java.awt.Color(204, 204, 204));
        maxHBD.setForeground(new java.awt.Color(0, 18, 50));
        maxHBD.setText("3");
        maxHBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxHBDActionPerformed(evt);
            }
        });

        maxHBA.setBackground(new java.awt.Color(204, 204, 204));
        maxHBA.setForeground(new java.awt.Color(0, 18, 50));
        maxHBA.setText("3");

        maxLogp.setBackground(new java.awt.Color(204, 204, 204));
        maxLogp.setForeground(new java.awt.Color(0, 18, 50));
        maxLogp.setText("3");
        maxLogp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxLogpActionPerformed(evt);
            }
        });

        Biolabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        Biolabel.setForeground(new java.awt.Color(204, 204, 204));
        Biolabel.setText("Chemical Beauty (QED) threshold");

        bioThreshold.setBackground(new java.awt.Color(204, 204, 204));
        bioThreshold.setForeground(new java.awt.Color(0, 18, 50));
        bioThreshold.setText("0.45");
        bioThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioThresholdActionPerformed(evt);
            }
        });

        maxLogp1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        maxLogp1.setForeground(new java.awt.Color(204, 204, 204));
        maxLogp1.setText("Chemical Beauty (QED) weights");

        bioWeightscomboBox.setBackground(new java.awt.Color(0, 18, 50));
        bioWeightscomboBox.setForeground(new java.awt.Color(242, 240, 241));
        bioWeightscomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Max information", "Mean weights", "unweighted" }));
        bioWeightscomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioWeightscomboBoxActionPerformed(evt);
            }
        });

        applybtn.setBackground(new java.awt.Color(32, 47, 90));

        applylbl.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        applylbl.setForeground(new java.awt.Color(204, 204, 204));
        applylbl.setText("Apply");

        javax.swing.GroupLayout applybtnLayout = new javax.swing.GroupLayout(applybtn);
        applybtn.setLayout(applybtnLayout);
        applybtnLayout.setHorizontalGroup(
            applybtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applybtnLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(applylbl)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        applybtnLayout.setVerticalGroup(
            applybtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, applybtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        maxWeighttxt.setBackground(new java.awt.Color(204, 204, 204));
        maxWeighttxt.setForeground(new java.awt.Color(0, 18, 50));
        maxWeighttxt.setText("300");
        maxWeighttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxWeighttxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addComponent(maxLogp1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(bioWeightscomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SettingsPanelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logPcomboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bioThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maxLogp, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(maxHBA)
                                    .addComponent(maxHBD)
                                    .addComponent(maxWeighttxt)))))
                    .addGroup(SettingsPanelLayout.createSequentialGroup()
                        .addComponent(Biolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(applybtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logPcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxWeighttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxHBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxHBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxLogp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Biolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bioThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bioWeightscomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxLogp1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(applybtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        fragmentsPanel.setBackground(new java.awt.Color(30, 61, 118));

        dbScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        dbScrollPane1.setForeground(new java.awt.Color(0, 18, 50));
        dbScrollPane1.setOpaque(false);

        fragTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CD ID", "Formula", "Structural similarity", "Functional similarity", "Isomers?", "Substructure?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fragTable.setFocusable(false);
        fragTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        fragTable.setRowHeight(25);
        fragTable.setSelectionBackground(new java.awt.Color(222, 57, 95));
        fragTable.setSelectionForeground(new java.awt.Color(242, 241, 240));
        fragTable.setShowVerticalLines(false);
        fragTable.getTableHeader().setReorderingAllowed(false);
        fragTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fragTableMouseClicked(evt);
            }
        });
        fragTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fragTableKeyPressed(evt);
            }
        });
        dbScrollPane1.setViewportView(fragTable);

        javax.swing.GroupLayout fragmentsPanelLayout = new javax.swing.GroupLayout(fragmentsPanel);
        fragmentsPanel.setLayout(fragmentsPanelLayout);
        fragmentsPanelLayout.setHorizontalGroup(
            fragmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fragmentsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(dbScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        fragmentsPanelLayout.setVerticalGroup(
            fragmentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fragmentsPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(dbScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        southContainer.setLayer(homePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        southContainer.setLayer(importPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        southContainer.setLayer(databasepanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        southContainer.setLayer(SettingsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        southContainer.setLayer(fragmentsPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout southContainerLayout = new javax.swing.GroupLayout(southContainer);
        southContainer.setLayout(southContainerLayout);
        southContainerLayout.setHorizontalGroup(
            southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(databasepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(importPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(southContainerLayout.createSequentialGroup()
                    .addComponent(fragmentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        southContainerLayout.setVerticalGroup(
            southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, southContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(databasepanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(importPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(SettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(southContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(southContainerLayout.createSequentialGroup()
                    .addComponent(fragmentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        appName.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        appName.setForeground(new java.awt.Color(30, 61, 118));
        appName.setText("ChemDTB");

        version.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        version.setForeground(new java.awt.Color(100, 100, 76));
        version.setText("V 1.1");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Icon.png"))); // NOI18N

        javax.swing.GroupLayout northHomeLayout = new javax.swing.GroupLayout(northHome);
        northHome.setLayout(northHomeLayout);
        northHomeLayout.setHorizontalGroup(
            northHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northHomeLayout.createSequentialGroup()
                .addGroup(northHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northHomeLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(northHomeLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(version)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        northHomeLayout.setVerticalGroup(
            northHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northHomeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(version)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        northDatabase.setForeground(new java.awt.Color(30, 61, 118));
        northDatabase.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Search2.png"))); // NOI18N

        searchBox.setBackground(new java.awt.Color(214, 217, 223));
        searchBox.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        searchBox.setForeground(new java.awt.Color(30, 61, 118));
        searchBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 61, 118));
        jLabel10.setText("Search ChemDTB");

        javax.swing.GroupLayout northDatabaseLayout = new javax.swing.GroupLayout(northDatabase);
        northDatabase.setLayout(northDatabaseLayout);
        northDatabaseLayout.setHorizontalGroup(
            northDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northDatabaseLayout.createSequentialGroup()
                .addGroup(northDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northDatabaseLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10))
                    .addGroup(northDatabaseLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(northDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchBox)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(structurelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        northDatabaseLayout.setVerticalGroup(
            northDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northDatabaseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(55, 55, 55)
                .addGroup(northDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(northDatabaseLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, northDatabaseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(structurelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 61, 118));
        jLabel11.setText("Import to ChemDTB");

        javax.swing.GroupLayout northImportLayout = new javax.swing.GroupLayout(northImport);
        northImport.setLayout(northImportLayout);
        northImportLayout.setHorizontalGroup(
            northImportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northImportLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        northImportLayout.setVerticalGroup(
            northImportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northImportLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        appName1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        appName1.setForeground(new java.awt.Color(30, 61, 118));
        appName1.setText("Settings");

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Settings2.png"))); // NOI18N

        javax.swing.GroupLayout northSettingsLayout = new javax.swing.GroupLayout(northSettings);
        northSettings.setLayout(northSettingsLayout);
        northSettingsLayout.setHorizontalGroup(
            northSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northSettingsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(appName1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 469, Short.MAX_VALUE)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        northSettingsLayout.setVerticalGroup(
            northSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
            .addGroup(northSettingsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(appName1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        appName2.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        appName2.setForeground(new java.awt.Color(30, 61, 118));
        appName2.setText("Check similarity");

        version1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        version1.setForeground(new java.awt.Color(100, 100, 76));
        version1.setText("Type the fragment SMART here or drag and drop the molecule sd file");

        fragFileDragNDrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/SDFDragnDrop.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Search2.png"))); // NOI18N

        searchBoxFragments.setBackground(new java.awt.Color(214, 217, 223));
        searchBoxFragments.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        searchBoxFragments.setForeground(new java.awt.Color(30, 61, 118));
        searchBoxFragments.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchBoxFragments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxFragmentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout northFragmentsLayout = new javax.swing.GroupLayout(northFragments);
        northFragments.setLayout(northFragmentsLayout);
        northFragmentsLayout.setHorizontalGroup(
            northFragmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northFragmentsLayout.createSequentialGroup()
                .addGroup(northFragmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northFragmentsLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(appName2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(northFragmentsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(northFragmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(version1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(northFragmentsLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addGroup(northFragmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchBoxFragments)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(88, 88, 88)
                .addComponent(fragFileDragNDrop)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        northFragmentsLayout.setVerticalGroup(
            northFragmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(northFragmentsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(appName2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(version1)
                .addGap(26, 26, 26)
                .addGroup(northFragmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(northFragmentsLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(northFragmentsLayout.createSequentialGroup()
                        .addComponent(searchBoxFragments, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, northFragmentsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fragFileDragNDrop)
                .addGap(35, 35, 35))
        );

        northcontainer.setLayer(northHome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        northcontainer.setLayer(northDatabase, javax.swing.JLayeredPane.DEFAULT_LAYER);
        northcontainer.setLayer(northImport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        northcontainer.setLayer(northSettings, javax.swing.JLayeredPane.DEFAULT_LAYER);
        northcontainer.setLayer(northFragments, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout northcontainerLayout = new javax.swing.GroupLayout(northcontainer);
        northcontainer.setLayout(northcontainerLayout);
        northcontainerLayout.setHorizontalGroup(
            northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(northHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northImport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northFragments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        northcontainerLayout.setVerticalGroup(
            northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(northHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northDatabase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northImport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(northcontainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(northFragments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DataBase/Images/Close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backGroundLayout = new javax.swing.GroupLayout(backGround);
        backGround.setLayout(backGroundLayout);
        backGroundLayout.setHorizontalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(southContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(northcontainer)
                    .addGroup(backGroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close)))
                .addGap(0, 0, 0))
            .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backGroundLayout.createSequentialGroup()
                    .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
        backGroundLayout.setVerticalGroup(
            backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backGroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close)
                .addGap(0, 0, 0)
                .addComponent(northcontainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(southContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(backGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backGroundLayout.createSequentialGroup()
                    .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 974, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void leadLiknessActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void lipinskiActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void importbtnMouseClicked(java.awt.event.MouseEvent evt) {                                       
        databasepanel.setVisible(false);
        importPanel.setVisible(true);
        homePanel.setVisible(false);
        northDatabase.setVisible(false);
        northHome.setVisible(false);
        northImport.setVisible(true);
    }                                      

    private void homebutnMouseClicked(java.awt.event.MouseEvent evt) {                                      
        databasepanel.setVisible(false);
        importPanel.setVisible(false);
        homePanel.setVisible(true);
       
        northDatabase.setVisible(false);
        northHome.setVisible(true);
        northImport.setVisible(false);
    }                                     

    private void databasebtnMouseClicked(java.awt.event.MouseEvent evt) {                                         
        databasepanel.setVisible(true);
        importPanel.setVisible(false);
        homePanel.setVisible(false);
        northDatabase.setVisible(true);
        northHome.setVisible(false);
        northImport.setVisible(false);


    }                                        

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {                                      
        int xCor = evt.getXOnScreen();
        int yCor = evt.getYOnScreen();
        
        this.setLocation(xCor-mouseX, yCor-mouseY);
    }                                     

    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {                                      
        mouseX = evt.getX();
        mouseY = evt.getY();
    }                                     

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {                                   
        this.dispose();
    }                                  

    private void SettingsbtnMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void logPcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void maxHBDActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void bioThresholdActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bioWeightscomboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void maxLogpActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void maxWeighttxtActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void dbtableMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void dbtableKeyPressed(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void fragmentsbtnMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void searchBoxFragmentsActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void fragTableMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void fragTableKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
     javax.swing.JLabel Biolabel;
     javax.swing.JPanel SettingsPanel;
     javax.swing.JPanel Settingsbtn;
     javax.swing.JLabel aboutLabel;
     javax.swing.JLabel appName;
     javax.swing.JLabel appName1;
     javax.swing.JLabel appName2;
     javax.swing.JPanel applybtn;
     javax.swing.JLabel applylbl;
     javax.swing.JPanel backGround;
     javax.swing.JTextField bioThreshold;
     javax.swing.JComboBox<String> bioWeightscomboBox;
     javax.swing.JCheckBox bioavailability;
     javax.swing.JLabel close;
     javax.swing.JPanel databasebtn;
     javax.swing.JPanel databasepanel;
     javax.swing.JScrollPane dbScrollPane;
     javax.swing.JScrollPane dbScrollPane1;
     javax.swing.JTable dbtable;
     javax.swing.JLabel dragNDroplbl;
     javax.swing.JPanel exportbtn;
     javax.swing.JLabel fragFileDragNDrop;
     javax.swing.JTable fragTable;
     javax.swing.JPanel fragmentsPanel;
     javax.swing.JPanel fragmentsbtn;
     javax.swing.JLabel gettingStartedLbl;
     javax.swing.JPanel homePanel;
     javax.swing.JPanel homebutn;
     javax.swing.JPanel importPanel;
     javax.swing.JPanel importbtn;
     javax.swing.JLabel importlbl;
     javax.swing.JLabel jLabel1;
     javax.swing.JLabel jLabel10;
     javax.swing.JLabel jLabel11;
     javax.swing.JLabel jLabel12;
     javax.swing.JLabel jLabel13;
     javax.swing.JLabel jLabel14;
     javax.swing.JLabel jLabel15;
     javax.swing.JLabel jLabel16;
     javax.swing.JLabel jLabel17;
     javax.swing.JLabel jLabel18;
     javax.swing.JLabel jLabel19;
     javax.swing.JLabel jLabel2;
     javax.swing.JLabel jLabel20;
     javax.swing.JLabel jLabel21;
     javax.swing.JLabel jLabel22;
     javax.swing.JLabel jLabel23;
     javax.swing.JLabel jLabel3;
     javax.swing.JLabel jLabel4;
     javax.swing.JLabel jLabel5;
     javax.swing.JLabel jLabel6;
     javax.swing.JLabel jLabel7;
     javax.swing.JLabel jLabel8;
     javax.swing.JLabel jLabel9;
     javax.swing.JSeparator jSeparator1;
     javax.swing.JSeparator jSeparator2;
     javax.swing.JCheckBox leadLikness;
     javax.swing.JCheckBox lipinski;
     javax.swing.JComboBox<String> logPcomboBox;
     javax.swing.JLabel logo;
     javax.swing.JLabel logo1;
     javax.swing.JTextField maxHBA;
     javax.swing.JTextField maxHBD;
     javax.swing.JTextField maxLogp;
     javax.swing.JLabel maxLogp1;
     javax.swing.JTextField maxWeighttxt;
     javax.swing.JPanel northDatabase;
     javax.swing.JPanel northFragments;
     javax.swing.JPanel northHome;
     javax.swing.JPanel northImport;
     javax.swing.JPanel northSettings;
     javax.swing.JLayeredPane northcontainer;
     javax.swing.JTextField searchBox;
     javax.swing.JTextField searchBoxFragments;
     javax.swing.JPanel sidePanel;
     javax.swing.JLayeredPane southContainer;
     javax.swing.JLabel structurelbl;
     javax.swing.JLabel titleBar;
     javax.swing.JLabel version;
     javax.swing.JLabel version1;
     javax.swing.JLabel viewDBlbl;
    // End of variables declaration                   
}
